"""initial migration

Revision ID: e19b566170f2
Revises: ebd1afccd78b
Create Date: 2023-06-05 17:11:42.023514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19b566170f2'
down_revision = 'ebd1afccd78b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
